#!/bin/bash

# We don't translate other people's work.
GOTO="/tmp/anti-msg-stash"
mkdir -p $GOTO
mv pythonenv $GOTO/

./utils/lang/unpack

/tmp/anti-msg-stash/pythonenv/bin/python ./inkscape/manage.py makemessages -a $@

./utils/lang/pack

mv $GOTO/* .
rmdir $GOTO

