#!/bin/bash

GOTO="/tmp/anti-msg-stash"
mkdir -p $GOTO
mv pythonenv $GOTO/

./utils/lang/unpack

# pythonenv is gone, don't use it here
./inkscape/manage.py makemessages -a $@

mv locale/en/LC_MESSAGES/django.po locale/django.pot
rm -fr locale/en/LC_MESSAGES

./utils/lang/pack

mv $GOTO/* .
rmdir $GOTO

