#!/bin/bash

GOTO="/tmp/anti-msg-stash"
mkdir -p $GOTO
mv pythonenv $GOTO/

./utils/lang/unpack

/tmp/anti-msg-stash/pythonenv/bin/python ./inkscape/manage.py makemessages -a $@

mv locale/en/LC_MESSAGES/django.po locale/django.pot
rm -fr locale/en/LC_MESSAGES

./utils/lang/pack

mv $GOTO/* .
rmdir $GOTO

