#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..
MANAGE="$DIR/utils/manage"
DEST="$DIR/data/backup"

mkdir -p $DEST/cms_db
mkdir -p $DEST/media

DATE=day-`date --iso`.json.gz

cd $DEST/cms_db

# Make a backup of the cms database and put it into a gz json file
# Don't make a copy of any other databases or tables from django.
$MANAGE dumpdata cms djangocms_text_ckeditor reversion menus mptt sekizai \
                djangocms_file djangocms_picture djangocms_snippet djangocms_link cmsplugin_news \
                cmsplugin_pygments cmsplugin_launchpad cmsplugin_brochure \
    | gzip -9 > $DATE


cd $DEST/cms_db

# Create hard links of all the backups
ln -f $DATE "$DIR/data/media/content.json.gz"
ln -f $DATE week-`date +%Y-%W`.json.gz
ln -f $DATE month-`date +%Y-%m`.json.gz
ln -f $DATE year-`date +%Y`.json.gz

# Remove any days older than 14 days
find . -name "day-*.json.gz" -mtime +14 -exec rm {} \;

# Remove any weeks older than 6 weeks
find . -name "week-*.json.gz" -mtime +42 -exec rm {} \;

# Remove any months older than a year
find . -name "month-*.json.gz" -mtime +256 -exec rm {} \;

# Never remove year backups
# find . -name "year-*.json.gz" -mtime +EEEE -exec rm {} \;

cd $DIR/data

DATE=$DEST/media/`date +%Y-%W`

if [ ! -d "$DATE" ]; then
  # Make a backup of all the uploaded media here, archived once per week
  cp -al media $DATE

  # There is room here for cleaning up old media uploads similar to the cms_db
fi

