#!/bin/bash

#
# Copyright 2013, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..
MANAGE="$DIR/utils/manage"
DEST="$DIR/data/backup"

mkdir -p $DEST/cms_db
mkdir -p $DEST/media

DATE=day-`date --iso`.json.gz

cd $DEST/cms_db

# Make a backup of the cms database and put it into a gz json file
# Don't make a copy of any other databases or tables from django.
$MANAGE dumpdata cms djangocms_text_ckeditor menus sekizai \
                djangocms_file djangocms_picture \
                djangocms_link cmsplugin_news \
                cmstabs \
    | gzip -9 > $DATE

# This group dump does open us up to a security hole as it lets
# anyone know how our groups are set up on live. (but we need to test)
$MANAGE dumpdata auth.Group -n | gzip -9 > $DIR/data/media/groups.json.gz

cd $DEST/cms_db

# Create hard links of all the backups
ln -f $DATE "$DIR/data/media/content.json.gz"
ln -f $DATE week-`date +%Y-%W`.json.gz
ln -f $DATE month-`date +%Y-%m`.json.gz
ln -f $DATE year-`date +%Y`.json.gz

# Remove any days older than 14 days
find . -name "day-*.json.gz" -mtime +14 -exec rm {} \;

# Remove any weeks older than 6 weeks
find . -name "week-*.json.gz" -mtime +42 -exec rm {} \;

# Remove any months older than a year
find . -name "month-*.json.gz" -mtime +256 -exec rm {} \;

# Never remove year backups
# find . -name "year-*.json.gz" -mtime +EEEE -exec rm {} \;

cd $DIR/data

DATE=$DEST/media/`date +%Y-%W`

if [ ! -d "$DATE" ]; then
  # Make a backup of all the uploaded media here, archived once per week
  cp -al media $DATE

  # There is room here for cleaning up old media uploads similar to the cms_db
fi

