#!/bin/bash

#
# Copyright 2015, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

#set -e

TARGET="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

if [ -f "data/deployment" ]; then
    source "data/deployment"
else
    echo "Local deployment: $TARGET"
fi

TEST=$@
export FORCE=0
export DOC_SOURCE="/tmp/inkscape-docs-export-website"
export DOC_TARGET="$TARGET/data/media/doc"

cd $TARGET

if [ ! -d "$DOC_TARGET" ]; then
    echo "Target doesn't exist: $DOC_TARGET, Creating..."
    mkdir -p $DOC_TARGET
fi

if [ ! -d "$DOC_SOURCE" ]; then
    echo "Can't find docs in $DOC_SOURCE, Downloading..."
    cd `dirname $DOC_SOURCE`
    git clone https://gitlab.com/inkscape/inkscape-docs-export-website.git &> /dev/null
    export FORCE=1
fi

if [ ! -d "$DOC_SOURCE" ]; then
    echo "Something went wrong with the download!"
    exit 1
fi

cd "$DOC_SOURCE"

if [ -d $DOC_TARGET ]; then
  git pull &> /dev/null
  if [[ $? == 0 || $FORCE == 1 ]]; then
    echo "New revisions found, updating!"
    echo "Sending docs to ${DOC_TARGET}..."
    rsync -ua $TEST --exclude='.bzr/' --delete . $DOC_TARGET
    git log -1 --date=local --format="%cd (%h)" > $DOC_TARGET/revision
  else
    echo "Docs alrady up to date!"
  fi
fi
