#!/bin/bash

#
# Copyright 2015, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

#set -e

DIR="$( cd "$( dirname "${BASH_DOCS[0]}" )" && pwd )"
cd $DIR/../

TEST=$@
export DOCS="/tmp/docs"
source "data/deployment"
export DOC_TARGET="$TARGET/data/media/doc"

if [ ! -d "$DOC_TARGET" ]; then
    echo "Target doesn't exist: $DOC_TARGET"
    exit 2
fi

if [ ! -d "$DOCS" ]; then
    echo "Can't find docs in $DOC_SOURCE"
    exit 1
fi

cd $DOCS

if [ -d $DOC_TARGET ]; then
  bzr pull --overwrite | grep Now\ on\ revision &> /dev/null
  if [[ $? == 0 ]]; then
    echo "New revisions found, updating!"
    echo "Sending docs to ${DOC_TARGET}..."
    rsync -ua $TEST --exclude='.bzr/' --delete . $DOC_TARGET
    bzr revno > $DOC_TARGET/revision
  else
    echo "Docs alrady up to date!"
  fi
fi
