#!/bin/bash

#
# Copyright 2013, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

#set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR/../

if [ ! -f "data/deployment" ]; then
    echo "Can not deploy a server instance."
    echo "the server information has not been set."
    exit 1
fi

TEST=$@ #"--dry-run"
SOURCE="/tmp/code"
source "data/deployment"

if [ ! -d "$TARGET" ]; then
    echo "Target doesn't exist: $TARGET"
    exit 2
fi

EX="$TARGET/keep-local.conf"
if [ ! -f "$EX" ]; then
    echo "!!!!!!!!!"
    echo "!"
    echo "! Excludes file not set, deployment will delete all data every time!"
    echo "!"
    echo "!!!!!!!!!"
fi

if [ ! -d "$SOURCE" ]; then
    SOURCE="./"
    exit 1
fi

SETTINGS="inkscape/settings.py"
REQUIRES="utils/requirements.txt"

PYTHON="./pythonenv/bin/python"
PIP="./pythonenv/bin/pip"

cd $SOURCE

bzr pull --overwrite | grep Now\ on\ revision &> /dev/null
if [ -d $TARGET ]; then
  if [[ $? == 0 ]]; then
    echo "New revisions found, updating!"
    rsync -rtuv $TEST --delete --exclude-from="$EX" . $TARGET
    rsync -rtuv $TEST data/ $TARGET/data
    bzr revno > $TARGET/data/revision
    bzr log -r119.. -n0 > $TARGET/data/revision.log
  fi
fi

cd $TARGET

./utils/update

./utils/manage clear_fastly_cache

touch ./data/wsgi.conf

