#!/bin/bash
set -e

mkdir -p data/media

command -v virtualenv &> /dev/null || {
  command -v apt-get &> /dev/null || {
    echo "I require pythonenv, but it is not installed. Aborting."
    exit 1;
  }
  sudo apt-get install python-virtualenv
}

python ./utils/python-bedeveled || {
  command -v apt-get &> /dev/null || {
    echo "I require python headers, but they are not installed. Aborting."
    exit 1;
  }
  sudo apt-get install python-dev
}

MANAGE="./utils/manage"

# Create tables, migrations etc
./utils/update

$MANAGE loaddata $PWD/utils/datums/auth.json
echo ""
echo "Default 'admin' user added, password: '123456' (delete on live deployments)"
echo ""

$MANAGE loaddata $PWD/utils/datums/licenses.json
$MANAGE loaddata $PWD/utils/datums/categories.json
$MANAGE loaddata $PWD/utils/datums/quota.json

./utils/refresh-cms #staging.

./utils/refresh-geoip

