#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/..

if [ ! -d "$DIR/pythonenv" ]; then
  echo "VirtualEnv not found, trying to set one up..."
  echo "Failed! I didn't write this part yet!"
fi

if [ -f "$DIR/manage.py" ]; then
  $DIR/pythonenv/bin/python $DIR/manage.py $@
else
  $DIR/pythonenv/bin/python $DIR/*/manage.py $@
fi

