#!/bin/bash

if [ -d "../pythonenv" ]; then
  cd ..
fi

if [ ! -d "./pythonenv" ]; then

print "VirtualEnv not found, trying to set one up..."

print "Failed! I didn't write this part yet!"

fi

if [ -f "manage.py" ]; then
  ./pythonenv/bin/python manage.py $@
else
  ./pythonenv/bin/python */manage.py $@
fi

