#!/bin/bash
set -e

wget -q https://${1}inkscape.org/media/content.json.gz -O /tmp/contents.json.gz --no-check-certificate
gunzip -c /tmp/contents.json.gz \
 | ./utils/migrate-backup - > /tmp/content_reformed.json

./utils/manage reset --noinput cms cmsplugin_news cmsplugin_pygments
./utils/manage loaddata /tmp/content_reformed.json

