#!/bin/bash

#
# Copyright 2014, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

# Does the same as syncdb but adds columns and such. Not a migration tool (use south!)
# only useful during development to presever data while changing model structures.
#
set -e

OUTPUT=".db.$1.json"

if [ -n "$1" ]; then
  echo "SyncPlus for APP '$1'"
  ./utils/manage dumpdata $1 > $OUTPUT
  echo " 1. Backup of '$1' complete."
  echo ""
  read -p "    Press [Enter] key when model is updated..."
  echo ""
  ./utils/manage reset $1
  echo " 2. Structure for '$1' reset to new model"
  ./utils/manage loaddata $OUTPUT
  echo " 3. Data for '$1' reloaded into database"
else
  echo "$0 [app_name]"
fi

