#!/bin/bash
set -e

PIP="./pythonenv/bin/pip"
MANAGE="./utils/manage.py"
REQUIRES="./utils/requirements.txt"

if [ \( ! -e $PIP \) -o \( $REQUIRES -nt $PIP \) ]; then
    $PIP install --upgrade distribute
    $PIP install -r $REQUIRES
fi

if [ $REQUIRES -nt "data/updated.last" ]; then
    $MANAGE syncdb
    $MANAGE migrate
    touch "data/updated.last"
fi

