#!/bin/bash

DIR="data/locale"
mkdir -p $DIR
cd $DIR

if [ ! -e 'website' ]; then
    git clone https://gitlab.com/inkscape/inkscape-web-i18n.git website
    cd website/
else
    cd website/
    git fetch
fi

git checkout live

# data/revision.log relative path, pretty printing human readable / unix time
git log --format="------------------%n%nAUTHOR:%aN%nTIME:%at%nEMAIL:%aE%n%h : %s%n%aD%n" > ../../translators.log
cd ../../../
./utils/manage compilemessages

