#!/bin/bash

#
# Copyright 2013, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

PIP="./pythonenv/bin/pip"
MANAGE="./utils/manage"
REQUIRES="./utils/requirements.txt"

if [ ! -e $PIP ]; then
    echo "Installing new PIP..."
    virtualenv pythonenv -p /usr/bin/python2.7
    touch -d '+1 minute' $PIP
    touch -d '+2 minute' $REQUIRES
fi

if [ $REQUIRES -nt $PIP ]; then
    echo "Updating PythonEnv..."
    $PIP install --upgrade distribute >&1 | grep -v 'fooblah'
    $PIP install -r $REQUIRES 2>&1 | grep -v 'horyhar'
    touch $PIP
fi

./utils/update-pot

if [ -e '.bzr' ]; then
    bzr revno > ./data/revision
    bzr log -r119.. -n0 > ./data/revision.log
fi

echo "Updating inkscape-docs log"
bzr log lp:inkscape-docs -n0 > ./data/documentation.log

if [ "inkscape/settings.py" -nt ./data/updated.last ]; then
    echo "Updating Django..."
    echo " * migrate"
    $MANAGE migrate -v 0
    echo " * DONE"
    touch "data/updated.last"
else
  $MANAGE getauser &> /dev/null
  if [ "$?" != 0 ]; then
    if [ "$1" != "-u" ]; then
      rm ./data/updated.last
      $0 -u
      exit $?
    fi
  else
    echo "No updates needed."
  fi
fi 

$MANAGE collectstatic --noinput
echo ""
echo "Copied static files from pythonenv to local static"
echo ""

