#!/bin/bash

PIP="./pythonenv/bin/pip"
MANAGE="./utils/manage.py"
REQUIRES="./utils/requirements.txt"

if [ ! -e $PIP ]; then
    echo "Installing new PIP..."
    virtualenv pythonenv -p /usr/bin/python2.7
    touch -d '+1 hour' $REQUIRES
fi

if [ $REQUIRES -nt $PIP ]; then
    echo "Updating PythonEnv..."
    $PIP install --upgrade distribute &> /dev/null
    $PIP install -r $REQUIRES &> /dev/null
    touch $PIP
fi

if [ "inkscape/settings.py" -nt ./data/updated.last ]; then
    echo "Updating Django..."
    $MANAGE syncdb 2> /tmp/.issues
    $MANAGE migrate 2>> /tmp/.issues
    touch "data/updated.last"
fi

#if grep -q ImportError "/tmp/.issues"; then
#    echo "Something went wrong! Removing pythonenv: please try again"
#    rm -fr ./pythonenv
#else
#    echo "Complete!"
#fi

